services:
  db:
    image: imresamu/postgis:16-3.5-bullseye
    container_name: bcfishpass-db
    command: postgres -c default_statistics_target=100 -c max_connections=20 -c max_locks_per_transaction=64 -c checkpoint_timeout=30min -c maintenance_work_mem=1GB -c effective_cache_size=16GB -c work_mem=500MB -c max_wal_size=10GB -c wal_buffers=16MB -c shared_buffers=8GB
    ports:
      - 8000:5432
    shm_size: 16gb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 1s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bcfishpass_test
  runner:
    build: docker/runner
    container_name: bcfishpass-runner
    volumes:
      - "./:/home/bcfishpass"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bcfishpass_test
      - AWS_ENDPOINT_URL=https://nrs.objectstore.gov.bc.ca
      - AWS_S3_ENDPOINT=nrs.objectstore.gov.bc.ca
      - AWS_VIRTUAL_HOSTING=FALSE
      - AWS_EC2_METADATA_DISABLED=true
      - CPL_VSISTDIN_BUFFER_LIMIT=-1
    depends_on:
      db:
        condition: service_healthy