name: bcfishpass
channels:
  - conda-forge
  - defaults
dependencies:
  - make
  - wget
  - zip
  - unzip
  - parallel
  - libpq
  - jq
  - python
  - pip
  - requests
  - owslib
  - awscli
  - psycopg2
  - sqlalchemy<2.0
  - gdal
  - rasterio
  - geopandas
  - geoalchemy2
  - rasterstats
  - scikit-image
  - seaborn
  - pip:
      - bcdata==0.7.6