name: ng-prod
run-name: ${{ github.actor }} Run bcfishpass on ng-prod and release fptwg distribution
on:
  schedule:
    - cron: '0 20 * * MON'
  workflow_dispatch:
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ENDPOINT_URL: https://nrs.objectstore.gov.bc.ca
  AWS_S3_ENDPOINT: nrs.objectstore.gov.bc.ca
  AWS_VIRTUAL_HOSTING: FALSE
  AWS_EC2_METADATA_DISABLED: True
  CPL_VSISTDIN_BUFFER_LIMIT: -1
concurrency:
  group: ng-prod
jobs:
  data-refresh:
    runs-on: ubuntu-latest
    environment: ng-prod
    container: ghcr.io/smnorris/bcfishpass:main
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run the jobs
        run: cd jobs && ./connect && ./load_weekly
  load-csv:
    runs-on: ubuntu-latest
    environment: ng-prod
    container: ghcr.io/smnorris/bcfishpass:main
    needs: data-refresh
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Load csv data, parameters
        run:  |
          jobs/connect
          cp parameters/example_newgraph/*csv parameters/
          jobs/load_csv
  load-xings:
    runs-on: ubuntu-latest
    environment: ng-prod
    container: ghcr.io/smnorris/bcfishpass:main
    needs: load-csv
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Load modelled crossings from archive
        run:  |
          jobs/connect
          jobs/load_modelled_stream_crossings
  model-xings:
    runs-on: ubuntu-latest
    environment: ng-prod
    container: ghcr.io/smnorris/bcfishpass:main
    needs: load-xings
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build modelled crossings
        run:  |
          jobs/connect
          jobs/model_00_stream_crossings
  model-access-natural:
    runs-on: ubuntu-latest
    environment: ng-prod
    container: ghcr.io/smnorris/bcfishpass:main
    needs: model-xings
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Access model - natural
        run:  |
          jobs/connect
          cd model/01_access && ./01_model_access_natural.sh bt ch_cm_co_pk_sk ct_dv_rb st wct
  model-access-anthropogenic:
    runs-on: ubuntu-latest
    environment: ng-prod
    container: ghcr.io/smnorris/bcfishpass:main
    needs: model-access-natural
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Access model - anthropogenic
        run:  |
          jobs/connect
          cd model/01_access
          ./02_model_access_anthropogenic.sh
          psql $DATABASE_URL -v ON_ERROR_STOP=1 -f sql/load_qa_observations_naturalbarriers.sql
  model-habitat-linear:
    runs-on: ubuntu-latest
    environment: ng-prod
    container: ghcr.io/smnorris/bcfishpass:main
    needs: model-access-anthropogenic
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
            fetch-tags: true
            fetch-depth: 0
      - name: Linear habitat model
        run:  |
          jobs/connect
          git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
          cd model/02_habitat_linear
          ./habitat_linear.sh
  release:
    runs-on: ubuntu-latest
    environment: ng-prod
    container: ghcr.io/smnorris/bcfishpass:main
    needs: model-habitat-linear
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Summarize and release
        run:  |
          jobs/connect
          psql $DATABASE_URL -c "select * from bcfishpass.wsg_crossing_summary_current" --csv > wsg_crossing_summary_current.csv
          psql $DATABASE_URL -c "select * from bcfishpass.wsg_linear_summary_current" --csv > wsg_linear_summary_current.csv
          aws s3 cp wsg_crossing_summary_current.csv s3://bchamp/wsg_crossing_summary_current.csv --acl public-read
          aws s3 cp wsg_linear_summary_current.csv s3://bchamp/wsg_linear_summary_current.csv --acl public-read
          jobs/release_fptwg
          psql $DATABASE_URL -c "select * from bcfishpass.qa_observations_ch_cm_co_pk_sk_st" --csv > qa_observations_ch_cm_co_pk_sk_st.csv
          psql $DATABASE_URL -c "select * from bcfishpass.qa_naturalbarriers_ch_cm_co_pk_sk_st" --csv > qa_naturalbarriers_ch_cm_co_pk_sk_st.csv
          aws s3 cp qa_observations_ch_cm_co_pk_sk.csv s3://bchamp/qa_observations_ch_cm_co_pk_sk_st.csv --acl public-read
          aws s3 cp qa_naturalbarriers_ch_cm_co_pk_sk.csv s3://bchamp/qa_naturalbarriers_ch_cm_co_pk_sk_st.csv --acl public-read