name: replicate
run-name: ${{ github.actor }} Replicate data from BC WFS / DRA to S3
on:
  schedule:
    - cron: '10 05 * * *'
  workflow_dispatch:
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  DRAPWD: ${{ secrets.DRAPWD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ENDPOINT_URL: https://nrs.objectstore.gov.bc.ca
  AWS_S3_ENDPOINT: nrs.objectstore.gov.bc.ca
  AWS_VIRTUAL_HOSTING: FALSE
  AWS_EC2_METADATA_DISABLED: True
  CPL_VSISTDIN_BUFFER_LIMIT: -1
concurrency:
  group: ng-prod
jobs:
  replicate:
    runs-on: ubuntu-latest
    environment: ng-prod
    container: ghcr.io/smnorris/bcfishpass:main
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run the jobs
        run: |
          jobs/connect

          DAY_OF_MONTH=$(date +'%d')
          DAY_OF_WEEK=$(date +'%u') # Monday = 1

          if [ "$DAY_OF_MONTH" = "15" ]; then
            echo "It is the 1st of the month, running monthly replication"
            cd jobs && ./replicate_bcgw M && ./replicate_dra
          fi

          if [ "$DAY_OF_WEEK" = "2" ]; then
            echo "It is Tuesday (UTC, Monday evening Pacific), running weekly replication and bcfishobs"
            cd jobs && ./replicate_bcgw W
            git clone https://github.com/smnorris/bcfishobs.git
            cd bcfishobs && git checkout v0.3.2
            ./process.sh
          fi